
name: release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options: [patch, minor, major]
        default: patch

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: js_action
          token: ${{ secrets.PUBLISH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup git
        run: |
                git config --global core.autocrlf input
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global pull.rebase false
                git config --global init.defaultBranch master
                git config --global core.symlinks true

      - name: Install willbe
        run: npm i -g willbe@stable

      - name: Install submodules
        run: will .npm.install

      - name: Run willbe publish
        run: will .publish action.release.${{ inputs.bump }}
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
